name: Benchmarking

on:
  pull_request:

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1'

      - name: Install Dependencies
        run: julia --project=benchmarks/ -e 'using Pkg; Pkg.instantiate()'

      - name: Run Benchmarks and Capture Output
        id: run_benchmarks
        run: |
          # Capture the output of versioninfo and benchmark results
          version_info=$(julia -e 'versioninfo()')
          benchmark_output=$(julia --project=benchmarks benchmarks/benchmarks.jl)

          # Format the output to match the desired comment structure
          combined_output="## Computer Information\n\`\`\`\n$version_info\n\`\`\`\n\n## Benchmark Report\n$benchmark_output\n"

          # Set the combined output as a GitHub Actions output
          echo "::set-output name=combined_output::$combined_output"

      - name: Find Existing Comment
        uses: peter-evans/find-comment@v3
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: github-actions[bot]

      - name: Post Benchmark Results as PR Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: "${{ steps.run_benchmarks.outputs.combined_output }}"
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          edit-mode: replace
